### ISSUE TITLE
Create a method that other communities can reproduce the report for themselves

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-dei#15]
Idea: Write a tutorial on how to measure the diversity in an open source community.

The tutorial might be structured as follows:

1. Decide what dimensions of diversity are interesting (combination of questions and demographics).
  + Provide guidance for which elements (e.g., metric, diagram, or theoretical investigation) might be interesting for a community to know.
2. Direct the user to the appropriate tools and methods for assessing diversity.
3. Provide a template where the results can be dropped in for reporting.

Include an example from beginning to end within the tutorial to make it tangible.

Possibly start with one Goal-Question to test the format.

?? How can we include an incentive to share the results with us. This would be helpful for comparisons and benchmarking. Can we add some gamification? Maybe have an anonymous sharing option.

**Comment by GeorgLink** [comment]
Ideas from this discussion thread made their way into the Tutorial we did at the Open Source Summit Europe 2018 in Edinburgh.

**Comment by GeorgLink** [comment]
**Consderations for creating a D&I report**

1. Planning and Preparation Phase
    1. Goal setting - Why do we want a D&I report? What questions do we have?
    1. Rally support: Stakeholder onboarding.
    1. Decide which metrics can best answer the questions your community has - look at CHAOSS resources.
    1. Prepare data collection strategy based on chosen metrics. 
    1. Plan dissemination strategy - What should the D&I report look like? Do we need a written report, a webinar, a conference presentation, or a blog post? When should it be announced? At what conferences can we discuss the results? What decisions are we informing and what format do the decision makers need the results in? 
    1. Feedback from the community before we start data collection
1. Data Collection Phase
    1. Methods may include
        1. Survey
        1. Interviews
        1. Observations at events
        1. Analyze community documents
        1. Run activity data collection software (e.g. GrimoireLab, Augur)
    1. Manage data
        1. Protect Privacy
        1. Keep track of different versions of the data
        1. Long-term storage for future report comparisons
1. Analysis Phase
    1. Put data in the report to align with the previously defined goals.
    1. Interpret the data using background information that would not be visible from the data alone.
    1. Consider how each data point is telling a story.
    1. Share a draft with the community for additional insights, stories, and feedback.
1. Dissemination Phase
    1. Publish finished report, tweet about it, disseminate it
    1. Share report on the CHAOSS community mailing list
    1. Prepare new iterations based on feedback
    1. Make decisions on resulting data

**Comment by emmairwin** [comment]
@GeorgLink is this completed (assuming as part of the conference sessions you've been running?)

**Comment by GeorgLink** [comment]
We ran several sessions on the subject. However, I was thinking that at some point we would make this "process" or these "recommended steps" part of our recommendation. Maybe an appendix to the released metrics? (on a related note, we also need to determine whether to release our [list of demographics](https://github.com/chaoss/wg-diversity-inclusion/tree/master/demographic-data) or whether we can [find another home for them that we can reference](https://github.com/drnikki/open-demographics/issues/64)).
