### ISSUE TITLE
Inclusivity & Accessibility - Section 508 compliance validation

### ISSUE THREAD

**Issue by mpgjon** [chaoss/wg-dei#192]
In the US, there is a fairly extensive list of technical accommodations for extending inclusiveness in Section 508 - https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/section-508-standards 

In context, it may be worth reviewing how the front-ends of CHAOSS products (Dashboards) comply with these standards so we're walking the talking:)

**Comment by GeorgLink** [comment]
:D that's a great idea. 

Tagging @sduenas and @sgoggins as respective leads for GrimoireLab and Augur.
Maybe create a separate issue for each software project?

**Comment by emmairwin** [comment]
Agree that this is a 'bucket of work' and should have multiple issues opened underneath it.   @mpgjon are you interested in in organizing this work into actionable pieces?

**Comment by mpgjon** [comment]
Sure can:)

**Comment by mpgjon** [comment]
I submitted two issues to start. I was thinking about submitting a third for supporting blind users, but at this time, I don't think there's any technical way to do ALT descriptions on dynamic graphs (dashboards).  Would love to hear about anything to the contrary, but I think that one may be a much longer term goal.

**Comment by sgoggins** [comment]
@mpgjon : I think the website for CHAOSS is addressing its own self internally.  There is also a released metric right now that includes document inclusivity. I think this an e closed.

**Comment by ElizabethN** [comment]
Closing this; can re-open if needed.
