### ISSUE TITLE
Use case for Time to First Response metric

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-dei#250]
The Common Metrics WG refined the "Time to First Response" metric. The following text is a use case of that metric for D&I:

> Making a community more welcoming: A community that wants to invite more contributors may look at the Time to First Response metric and make sure that new community members feel more welcomed by responding to them quickly. Conversely, a contribution that falls on deaf ears and is not responded to can create the feeling that a community is not welcoming to contributions. 

Should we create a new metric that builds on top of the common metric?

**Comment by emmairwin** [comment]
I think response is important for building healthy, welcoming communities which of course translates to inclusion, but I think we should be citing specific research related to D&I to ensure the goal-metrics are focused there.   

In Mozilla research, the D&I angle was not that response times were quick, so much as who had quick and meaningful responses.  For example, I've observed that those who are good at asking for specific help are served first, while those with less confidence/capital (etc) tend to just say 'hello' in the beginning, or hang back to observe.  D&I metrics IMO would focus on recognizing participation  'types' and being response to all. If that makes sense.

**Comment by germonprez** [comment]
I believe we have this covered in the Common Metric. If you would like to add a DEI component to the metric, please make suggestions in the Common Working Group.
