### ISSUE TITLE
New idea: Interview campaign with underrepresented groups in Open Source

### ISSUE THREAD

**Issue by jwflory** [chaoss/wg-dei#294]
# Summary

Create an informal process / template for someone to conduct a qualitative interview about Diversity and Inclusion in Open Source

# Background

In the 2020-06-24 CHAOSS D&I Working Group meeting, a new metric idea for Closed Captioning was mentioned for virtual events, since they are becoming more common in the times of COVID-19. On #a11y Twitter, there have been voices calling for Closed Captioning at events (local and virtual) for a while.

I feel like D&I metrics in open source have the most potential impact for underrepresented groups. So, the best way to design and iterate on inclusive metrics might be to conduct informal interviews on what we measure and how we could better capture the value of diversity and inclusion in a community.

# Details

This is a forecast of the work I think is required to carry out this task:

1. Create clear messaging / conversation resources about current D&I work
1. Brainstorm some common questions to encourage conversation and critique on the metrics
1. Organize call for participants / share among our personal networks with explicit invitations to underrepresented groups in Open Source
1. Collate feedback and map out next iteration

# Outcome

Better feedback loops on value added to ecosystem with metrics and discover gap areas that may be overlooked

**Comment by ElizabethN** [comment]
@jwflory This is a great writeup. Just to be clear, are you specifically looking at a11y issues, or D&I efforts in general? I really love the idea of partnering with other groups and individuals who are domain experts in these areas and asking for their input as we develop these metrics. I vote that we add this to the agenda for the next D&I Working Group meeting, and hopefully get an action plan in place and talk about this more. Will you be attending?

**Comment by jwflory** [comment]
I'll join the next D&I call :slightly_smiling_face:

**Comment by Erioldoesdesign** [comment]
When is this D&! call and how can I join too :D @ElizabethN 

I love this issue but in general, I think this repo could benefit from some labels that might help researchers/UX researchers discover this issue?

Also, I highly recommend looking into the [Secure UX checklist](https://static1.squarespace.com/static/5e28cfb6752be803fc51f907/t/5eaa5b9f4f2f3e5a01d381ba/1588222879354/Secure+UX+Checklist.pdf) for a guide/resource on how to do well...secure UX research!

https://www.secureux.design/

**Comment by germonprez** [comment]
Hey @Erioldoesdesign, the D&I call is at 10am CDT Wednesdays. Connection information here: https://chaoss.community/participate/

Thanks for the suggestion of tags (agreed) and the Secure UX checklist. I'm not familiar with that but would love to learn more :)

**Comment by ElizabethN** [comment]
Today in the DEI Working Group, we revisited this idea and decided that it still holds value, especially with the review of the older metrics. It would be great to interview others to see where we can improve our DEI metrics and where the areas are that have remained unaddressed. Let's keep this idea alive and revisit early 2022.

**Comment by Erioldoesdesign** [comment]
Happy to help on this again if it's being re-visited 😄

**Comment by ElizabethN** [comment]
In today's DEI call, we discussed the depth of a project like this and that it will be relatively time intensive. It's a big ask to have people schedule, run, and reflect on a set of interviews. We are going to pose this to the DEI Audit team for some guidance and potentially having that team direct this initiative.

**Comment by ElizabethN** [comment]
We talked about this again today, and decided to put this on the back burner for now, only because we do have a lot of metrics already in the queue, and this project could surface even more. We think we should resurface this maybe in about 6 months. It's still an awesome idea!

**Comment by jwflory** [comment]
@germonprez Seems like a good idea. Will there be an official CHAOSS presence there, either through speakers or with a booth? This could be one way to facilitate engagement around the interviews.

**Comment by germonprez** [comment]
Yes. We are going to have a 1/2 day CHAOSScon in Dublin. So there should be a few of us there.

**Comment by jwflory** [comment]
@germonprez Super. Then I think as part of the CHAOSScon, it would make sense to include this as part of the event planning to think on how we engage folks there. Especially if we have newcomers who are new to the project and our work.

**Comment by ElizabethN** [comment]
@Anita-ihuman has expressed interest in moving this forward! HOORAY! 🎉  She will start an initial first draft document with her thoughts on how this could roll out.

**Comment by jwflory** [comment]
Awesome! Thanks @Anita-ihuman on exploring this one. 🚀 When you are ready, we can share feedback with you on a draft in the weekly D.E.I. working group meeting. 😃

**Comment by Anita-ihuman** [comment]
https://docs.google.com/document/d/1_Gb6QNGL4b9lGc1xqpl9nEw4ub0edC-WwgiKR50MIfk/edit#

**Comment by jwflory** [comment]
@Anita-ihuman This draft proposal is amazing! Kudos!

We had a good feedback/editing session in the D.E.I. Working Group call today. We can always take a look at this again for another pass when you are ready. I would also be interested in helping conduct these interviews with people outside of the CHAOSS community using this structure as a model.

**Comment by Preshh0** [comment]
I volunteer to help out with these interviews @Anita-ihuman

**Comment by sgoggins** [comment]
@jwflory / @Anita-ihuman / @Preshh0 : I have a lot of papers and research experience spanning interview and trace data integration.

**Comment by Preshh0** [comment]
Sweet. Can they be made available to us?

**Comment by Anita-ihuman** [comment]
> @jwflory / @Anita-ihuman / @Preshh0 : I have a lot of papers and research experience spanning interview and trace data integration.
> 
> I made a more detailed comment in the doc.

Awesome. Please do share these resources with us.

**Comment by jwflory** [comment]
I will aim to catch next week's (21 September) working group meeting. It would be great for an update on this one! I haven't been able to make the last couple of meetings.

**Comment by Anita-ihuman** [comment]
@jwflory currently, we are wrapping up the [interview questions](https://docs.google.com/document/d/1gR_6AMDL0QT55ASwPLN3OEGVCzJS6ksfFRb880HU5jM/edit#heading=h.oe6lqfh43gb)and preparing for the IRB process.

**Comment by ElizabethN** [comment]
Just popping in here to say this project is still ongoing and the data is being analyzed. Thanks for all that you've done with this @Anita-ihuman! 😍

**Comment by ElizabethN** [comment]
@Anita-ihuman posted a lovely and thorough analysis of this on the [CHAOSS Blog](https://chaoss.community/unveiling-the-impact-dei-metrics-overcoming-social-barriers-in-open-source/), so I'm going to close this issue. Thank you once again for all your work here @Anita-ihuman!
