### ISSUE TITLE
Metric idea: Communication Inclusivity in Event Focus Area

### ISSUE THREAD

**Issue by bistaastha** [chaoss/wg-dei#299]
CHAOSS D&I Badging recently had a Pilot Testing phase.

During that time, @ElizabethN opened an issue for providing feedback for the process, which lives here - https://github.com/badging/event-diversity-and-inclusion/issues/8

A particular fraction of the feedback contained these questions that can be asked to a CHAOSS Badging Applicant:

```
  - is the event website accessible for visually and hearing impaired folks?
  - is the venue wheelchair friendly?
  - are there sign language interpreters or closed captioning available?
  - are there resources for visually impaired folks? (Volunteers to assist as guides, alternative versions of schedules in Braille or available besides just online?)
```

This part of the feedback can possibly be looked into and expanded upon to create a new Event focus area metric about how the talks and other conference material can be made more accessible.

**Comment by ElizabethN** [comment]
These are encompassed in our [Event Accessibility Metric](https://chaoss.community/kb/metric-event-accessibility%ef%bf%bc/).
