### ISSUE TITLE
Metric Idea: Documentation Time Diversity

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-dei#315]
This would be a new metric under the Project and Community focus area. 

The premise of the metric is to observe and measure how well documentation is broken down so that it can be read and engaged with in small blocks of time. No all people have the ability to spend extended periods of time with documentation and this metric would help better understand how projects have addressed this concern. 

@Erioldoesdesign --> Did I get this right :)

**Comment by Erioldoesdesign** [comment]
Sounds perfect! :D

**Comment by ElizabethN** [comment]
We are cleaning up some of these metric ideas and moving them to our central spreadsheet. Thanks everyone!
