### ISSUE TITLE
Metric Idea: Mode Alternatives / Communication Channels

### ISSUE THREAD

**Issue by jwflory** [chaoss/wg-dei#318]
_Discussed in [2020-10-07 meeting](https://docs.google.com/document/d/1MzDk84BL7FfHDxbFxJz39M72V2Hfc5Y6oCPhOl6woxo/edit#heading=h.edc1in398ch8)._

---

# Summary

Create a new metric about inclusivity of different Communication Channels for open community discussion

# Background

In today's WG meeting, we briefly discussed how inclusivity is a factor to consider when picking or using different synchronous or asynchronous communication tools. I mentioned a recent example from my work where I recently started working with blind colleagues, and had to evaluate how inclusive the tools and resources I maintain are for the blind.

I also mentioned how communities use different platforms, and the value of meeting people where they are. This is a perspective I see often as a co-maintainer of [TeleIRC](https://github.com/RITlug/teleirc), a tool to bridge IRC/Matrix channels and Telegram groups together. I think it is something that is not well-understood or discussed in the Open Source community.

# Details

I volunteered to kickstart a first draft using the [metrics template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md). Then, we can do the workshopping we do in the D&I meetings on the first draft and go from there.

To keep me responsible, I intend to have a first draft by the D&I WG meeting on Wednesday, 11 November.

# Outcome

Build understanding and awareness for how to make inclusivity a key consideration when picking communication tools for an open source project

**Comment by jwflory** [comment]
_Discussed in [2020-11-11 meeting](https://docs.google.com/document/d/1MzDk84BL7FfHDxbFxJz39M72V2Hfc5Y6oCPhOl6woxo/edit#heading=h.cxtbjm4xlqqz)_.

---

As promised, I shared my first draft in today's WG meeting: [Public Chat Rooms - CHAOSS D&I Metric (draft)](https://docs.google.com/document/d/1JEiA1OTyXBCaexgK_zxSx6eIXfOAdbMHjqzho0hlHSY/edit). We had time for a short collaborative brainstorm, but ran out of time to go deep on it. We will cover this one more in depth at next week's meeting.

**Comment by LawrenceHecht** [comment]
@germonprez right now, this PR is labeled as "Under Community Review" in the CHAOSS Metrics worksheet.  I'm assuming it should "Ready to be worked on", but I didn't make that change.

**Comment by ElizabethN** [comment]
I think this can be closed, as the metric was released a while ago.
