### ISSUE TITLE
Metric Idea: Language Diversity

### ISSUE THREAD

**Issue by king-gao** [chaoss/wg-dei#339]
**Question：** What language of community communication can be used more widely?
The open source community is a platform for multi-language communication. Members from different countries and languages communicate with each other. Therefore, language barriers may exist.
There are six official languages of the United Nations, namely Arabic, Chinese, English, French, Russian and Spanish，these languages are widely used.And English is probably the most widely spoken language.

**Answer：** Language communication in the community should be divided into two levels.
- **write and see:** Documents, code Comments,etc., entered by a computer and received by others with their eyes; shall we define this is Basic level, because It can be done if you are willing to take some time.
- **say and listen:** Meeting, communication, etc, spoken through the mouth and received by others ears;shall we define this is High level, because real-time performance is required.

**Metrics**: 
- How many languages do the community use in the documentation to get more people involved? 
- How many languages do the community use in the conference to get more people involved?

**Comment by germonprez** [comment]
Thanks for this @king-gao. I really like the idea of exploring language in more detail. We will certainly bring this up in the D&I meeting.

**Comment by germonprez** [comment]
Thanks @king-gao. We talked about this today in the D&I meeting. Right now, we have a few other related metrics that are released or under community review: 

https://chaoss.community/metric-documentation-accessibility/

The response with respect to language diversity was very positive. The things we will continue to talk about will be how we can incorporate what you propose with these new metrics.

**Comment by king-gao** [comment]
Thanks @germonprez , [Documentation Accessibility](https://chaoss.community/metric-documentation-accessibility/) is great!  I think it is larger than language diversity in Documentaion scope.

This metric gives me a good hint. Shall we consider from **information Accessibility**.
because in community , there are many different kinds of infomation style beside documentaion, like video, audio, picture, table and other rich text. 

**filter**: Even some information is not carried in the community, such as communication between two people at once meetup. But this scenario is hard to metrics. So we can metrics the **information Accessibility** scope which information are archived and can be queried.This can be used as a filter condition.

**Comment by LawrenceHecht** [comment]
I have a problem with the focus on "documentation". Accessibility to all types of info and communication is impacted by languages used as well as the other factors traditionally considered in the accessibility categories. 

So, I like @king-gao's idea about Info Accessibility. I am going to link to this thread in the approval comments for the Doc Access. release candidate thread.
