### ISSUE TITLE
Release Notes 2021-09

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-dei#351]
This issue was created to capture the continuous contribution notes. Insight from comments will be used to create the regular release notes.

Example comments could be:

name of new metric and date of release
descriptions of changes to existing metric
Changes to focus areas or restructuring of WG

**Comment by germonprez** [comment]
Documentation Discoverability is a new metric in the Project and Community focus area.

**Comment by ElizabethN** [comment]
Closing this since we had a successful release with all these metrics :tada:
