### ISSUE TITLE
Standard Structure for README.md in each WG repo

### ISSUE THREAD

**Issue by yash2002109** [chaoss/wg-dei#358]
Hi everyone,

While standardizing the repositories, I noticed that the [README](https://github.com/chaoss/wg-diversity-inclusion/blob/master/README.md) file of each working group has a different structure. After discussing with @GeorgLink, I have drafted a proposal for a common structure that can be implemented across these README files. I have also replicated the same as a [template](https://github.com/yash2002109/chaoss-workspace/blob/main/WG-README-template.md).

Link: https://docs.google.com/document/d/1pfipIiaemdtdiDQpvY7jOKhKzsv_3lXLLsbJiByl5GU/edit?usp=sharing

Please provide your thoughts and suggestions regarding the proposal.

**Comment by GeorgLink** [comment]
I think the DEI WG repo now uses the correct README format. 

@yash2002109, can you please confirm that this work is complete and we can close the issue?

**Comment by yash2002109** [comment]
Thanks, @GeorgLink,

In discussion with WGs, we decided to remove the meeting details from the README and redirect the user to the Participate section on the website. We also discussed with the community to add the `Chairs` instead of WG-maintainers. 

Also, please refer to the template: https://docs.google.com/document/d/1pfipIiaemdtdiDQpvY7jOKhKzsv_3lXLLsbJiByl5GU/edit
to make sure the order in which the information is presented gets followed.

It would be great if a WG member could take an AI to draft the README.

**Comment by GeorgLink** [comment]
Thanks @yash2002109 , we can leave the issue open until the WG has time to address it.

**Comment by ElizabethN** [comment]
The WG discussed this today, and there are a few PRs that we think addressed this #356 and Issue #346. Going to close this for now, but we can re-open if needed.
cc @GeorgLink @yash2002109

**Comment by GeorgLink** [comment]
Thanks for the Ping. I think we are all good for now!
