### ISSUE TITLE
A Few Great Ideas for Event Metrics

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-dei#361]
The following are some great ideas that we should consider for event metrics: 

- Agenda Content 
   - Sessions for DEI 
   - Events that bring together Diverse Attendees 
- Non-binary Restrooms / Nursing Rooms / Quiet Rooms 
- Communication and Pronoun Stickers (not preferred pronouns)

**Comment by ElizabethN** [comment]
We have included these ideas in our [Event Accessibility Metric](https://docs.google.com/document/d/1HfU5Xloq7X_UQMNqdvSSX2k6AoDIx8rdbWCb3Ar8m7M/edit). Thanks @germonprez!
