### ISSUE TITLE
Add Code of Conduct Enforcement to both CoC at Event and CoC at Project

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-dei#363]
This issue is to highlight that we need to add comments of enforcement to both the released metrics of: 

CoC at Event 

and 

CoC in Project

**Comment by sgoggins** [comment]
This is super important. Working group agrees.

**Comment by geekygirldawn** [comment]
The [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) sections about enforcement might give you some ideas for adding this to the metric.

**Comment by Nebrethar** [comment]
Valuable feedback, we need this in the next release!

**Comment by ElizabethN** [comment]
This is in the Code of Conduct for Project, but still needs to be added to the Code of Conduct for Events. We should add it when that metric is reviewed.

**Comment by ElizabethN** [comment]
@germonprez is starting the review doc for Code of Conduct for Events so we can add this as something we need to add. Going to close this issue 👍
