### ISSUE TITLE
Add "Equity" to the Readme

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/wg-dei#369]
This was a suggestion from a comment in the development of the Psychological Safety metric by @GeorgLink, who suggested that perhaps we should add "equity" to this resource here: https://github.com/chaoss/wg-diversity-inclusion/blob/master/demographic-data/README.md

Would that fit? What do we think about that? Would love to have a discussion about that here.

**Comment by Nebrethar** [comment]
I tried at this in #381 😁

**Comment by jwflory** [comment]
#381 is merged. Closing this issue as complete! 🌊
