### ISSUE TITLE
Metric Idea: Inclusion of Color Blind

### ISSUE THREAD

**Issue by nicorikken** [chaoss/wg-dei#372]
[Color blindness](https://en.wikipedia.org/wiki/Color_blindness) is remarkably common. At work I have seen awkward scenario's where graphs or slides are shown to stakeholders, only to find out they aren't able to distinguish the green and red lines due to their color blindness. I found [this blogpost](https://venngage.com/blog/color-blind-friendly-palette/) to give an elaborate overview of the issue and possible measures.

**Some general advice for measures:**
* Avoid relying on color for a visual distinction, whether they are icons or graphs. Lightness or patterns can be alternatives.
* If making distinction with color, use a color scheme that fits color blind.'
  * E.g. [Jenkins](https://www.jenkins.io/) uses blue/red to signal correct/false rather than the the troublesome green/red.

**Ideas for metrics:**
* Are the used visuals readable by color blind? (e.g. event announcement, event slides, documentation, resulting software)
* Is checking for color blindness embedded in the community? (e.g. decent color scheme provided and adoption is checked with changes) (_the need of embedding is a generic remark for all metrics_)

**Larger scope:** I can see this becoming part of a larger metrics like 'inclusion of visually impaired', whether blind, partially blind, or even [dyslexic](https://opendyslexic.org/about).

**Comment by ElizabethN** [comment]
@nicorikken we have added these considerations to our [Event Accessibility Metric](https://docs.google.com/document/d/1HfU5Xloq7X_UQMNqdvSSX2k6AoDIx8rdbWCb3Ar8m7M/edit), and included a link to the blog post you mentioned, under the "references" section of the metric. Thanks again for bringing this up!

**Comment by germonprez** [comment]
Suggestion to create a new Project Accessibility metric that can include color blindness as addressed within a project. Similar to Event Accessibility.

**Comment by ElizabethN** [comment]
We moved this metric idea to the central spreadsheet and are tracking it there. Thanks everyone!
