### ISSUE TITLE
Metric Idea: Decision Making to Governance Focus Area

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-dei#382]
In talking about inclusion in OS, and just running a project a question that comes up a lot is, how do we setup for decision making.

I think this should be added to 'governance' under diversity and inclusion metrics, and that one of the resources be:  
https://github.com/github/MVG   (there may be more but this is helpful I find to help unstick people).

If you want to give feedback, I can submit a PR if others agree. thanks

**Comment by emmairwin** [comment]
Governance!  (sorry).  Decision making is central in governance, and we have nothing around it yet (that I can see)

https://github.com/chaoss/wg-dei/tree/main/focus-areas/governance#readme

**Comment by ElizabethN** [comment]
I believe this is covered in the [Communication Transparency](https://chaoss.community/kb/metric-communication-transparency/) and [Inclusive Leadership](https://chaoss.community/kb/metric-inclusive-leadership/) metrics, so I'm going to close this for now. Feel free to re-open if I got that wrong! Thanks everyone!!
