### ISSUE TITLE
Metric Idea: Contributor Payment Dynamic

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/wg-dei#383]
We originally talked about this in #381.

All credit for this idea goes to @emmairwin, and then @germonprez to make an issue, and then @GeorgLink to propose making it a metric! I am only the delivery service 😁 

I'm also interested in making this into a metric. I'm not sure what it would look like in detail. Let's have a discussion about it! 🎉

**Comment by emmairwin** [comment]
totally - I love the Drupal credits system, and that;s great to see our friends at GitLab thinking of this too.
I think this type of functionality is complementary in that it helps projects recognize contributors, but also better understand their ecosystems, this information can help better understand the ecosystem, and make informed decisions.

This was orginal part of diversity metric, but I don't think it really belongs there as it is more about the ecosystem ?

**Comment by ElizabethN** [comment]
We are cleaning up some of these metric ideas and moving them to the central spreadsheet for further tracking. Thanks everyone!
