### ISSUE TITLE
In-Progress: Inclusive Naming Checklist

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/wg-dei#395]
_This list was informed by the[ Inclusive Naming Initiative](https://inclusivenaming.org/) to improve the language used in our metrics and documentation. It can be used to assess any documentation for inclusive naming in the CHAOSS GitHub organization._

Hey folks! Here is the first draft of some naming to review in our metrics and documentation. Will discuss in 1/18/2022 community call. I will try to keep up with any new terms added to the Inclusive Naming lists. Please check the links for additional context.

Each checkbox indicates a term that we may find and will want to replace. Please check the box only if the presented word is no longer present in the document.

- [Tier 1: Replace Immediately](https://inclusivenaming.org/word-lists/tier-1/)
  - [ ] Abort / Abortion
  - [ ] Whitelist / Blacklist
  - [ ] Master / Slave
- [Tier 2: Strongly Consider Replacing](https://inclusivenaming.org/word-lists/tier-2/)
  - [ ] Sanity Check / Sanity Test
- [Tier 3: Recommendations to Replace](https://inclusivenaming.org/word-lists/tier-3/)
  - [ ] Segregate

**Comment by germonprez** [comment]
Now this is a great idea for GSoD.

**Comment by germonprez** [comment]
Could be part of the review process -- Proposal: include in the checklist.

**Comment by germonprez** [comment]
Also, the list could provide a good first issue for people looking to help with improving CHAOSS documentation.

**Comment by ElizabethN** [comment]
We discussed this in today's community meeting - we have some thoughts on next steps for incorporating this more into the CHAOSS metrics, which we will bring to the community meeting.

**Comment by ElizabethN** [comment]
@germonprez do you think we could add the consideration for inclusive naming into our new issue template as just a bullet point for folks to be mindful of when releasing a new metric?

**Comment by germonprez** [comment]
Tier 1 terms: 

[abort](https://inclusivenaming.org/word-lists/tier-1/abort/)
[blackhat-whitehat](https://inclusivenaming.org/word-lists/tier-1/blackhat-whitehat/)
[cripple](https://inclusivenaming.org/word-lists/tier-1/_cripple/)
[master](https://inclusivenaming.org/word-lists/tier-1/_master/)
[master-slave](https://inclusivenaming.org/word-lists/tier-1/_master-slave/)
[Tribe](https://inclusivenaming.org/word-lists/tier-1/tribe/)
[whitelist](https://inclusivenaming.org/word-lists/tier-1/whitelist/)

**Comment by ElizabethN** [comment]
Website checked today during the DEI working group call (yay!) :tada:
Still to be checked: software (augur, grimoirelab, slackbots, badging bots)

**Comment by sgoggins** [comment]
Augur is updated.

**Comment by germonprez** [comment]
Quick check on bots and okay

**Comment by germonprez** [comment]
There are some issues when the term is a programming keyword (e.g., abort).

**Comment by germonprez** [comment]
If people have an interest, please help out by identifying where these Tier 1 words may be present in the CHAOSS project.

**Comment by peculiaruc** [comment]
@germonprez @sgoggins , I made my search on the repos, I stand to be corrected if the search should be done on the repo or on the website of  each project.

GrimoireLad:

1. abort -  https://github.com/chaoss/grimoirelab/issues/547 etc.
2. blackhat-whitehat - not found
3. cripple - not found
4. mastr - https://github.com/chaoss/grimoirelab/issues/598 etc.
5. master-slave - not found
6. Tribe - https://github.com/chaoss/grimoirelab/issues/571 etc.
7. whitelist - not found

**Comment by ElizabethN** [comment]
@peculiaruc just doing a little cleanup on some repos today, and I'm wondering if I can close this issue. I think we made all the changes we could that were straightforward. I think the rest of them will require quite a bit of work and discussion. is it ok if I close this issue?

**Comment by peculiaruc** [comment]
Yes, we can close it now.

**Comment by ElizabethN** [comment]
Thank you so much @peculiaruc for your work on this! 🌟
