### ISSUE TITLE
Revising Metric: Family Friendliness

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-dei#431]
### Name of the Metric Being Revised
Family Friendliness
https://chaoss.community/metric-family-friendliness/

Submit PRs to this document https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/family-friendly.md

### Link to Original Metric Release Issue
https://github.com/chaoss/wg-dei/issues/256

### Specific Metric Details that Require Attention

- Revisit the formatting in the Data Collection Strategy section 
- "IF" in the 4th interview question is currently CAPS
- Check out the spreadsheet remark
- Add date of last review
- Change filename to match the name of the metric (family-friendliness.md)

#### Process

- [x] Create the “revising metric” labeled issue in the authoring WG’s repo for comments during review period
- [x] Create pull request of revised metric to WG’s repo (after checking Content Quality and Technical Requirements below)
- [x] Add the metric revision to release notes issue in working group repo
- [x] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit) to indicate that the revised metric is under review
- [x] Create issue in [CHAOSS/Translations repository](https://github.com/chaoss/translations) to kick-off translation to other languages (please use the the translation issue template)
- [ ] "Metric Candidate Release" label added to the metric release candidate issue when fully ready fo release

**When above steps are completed:**

- [ ] Announce new/updated metric on mailing list, newsletter, community Zoom call, and Twitter. This can be coordinated with the community manager and can be done as a collective of all revised metrics from the CHAOSS community. 

#### Content Quality (check all that apply)

- [ ] Date of last review has been added to the revised metric at the bottom of the markdown file (month/year)
- [x] Formatting changes have been made 
- [x] Minor editorial changes have been made 
- [ ] Major editorial changes have been made 
- [ ] Metric adheres to the current [metrics template](https://github.com/chaoss/community/blob/main/templates/metric-template.md)
- [ ] Metric name has changed and necessary updates are made to the WG README table and metrics tracking spreadsheet

#### Technical Requirements for any Revisions

- [ ] Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- [ ] Images are included using markdown and absolute path links (as described in the metrics template)
- [ ] Images have at least one empty line above and below them
- [ ] Images are placed in image folder and followed [naming convention](https://github.com/chaoss/community/blob/main/templates/metric-template.md)
- [ ] If new a focus area is created, ensure focus area is added to wg repo readme and focus area folder readme
- [x] There is no HTML code in the metrics markdown file

**Comment by TejasMate** [comment]
Issues solved
"IF" in the 4th interview question is currently CAPS
Add date of last review
Check out the spreadsheet remark
Change filename to match the name of the metric (family-friendliness.md)

Not solved due to bug in rendering:
Revisit the formatting in the Data Collection Strategy section

**Comment by sgoggins** [comment]
#444 finishes the updates in this issue.
