### ISSUE TITLE
Contributor Community Diversity link is broken

### ISSUE THREAD

**Issue by marimeireles** [chaoss/wg-dei#447]
It's pointing to [Contributor Community Diversity](https://github.com/chaoss/wg-dei/blob/main/focus-areas/contributor-community-diversity).

**Comment by germonprez** [comment]
Thanks @marimeireles - could you provide the page where you found the broken link?

**Comment by marimeireles** [comment]
Oops, sorry. The main readme https://github.com/chaoss/wg-dei#focus-areas

**Comment by ElizabethN** [comment]
This has been fixed in this PR https://github.com/chaoss/wg-dei/pull/449. Thanks for pointing this out, @marimeireles! 🙌
