### ISSUE TITLE
Amending the GitHub README to reflect mailing list status

### ISSUE THREAD

**Issue by divya-mohan0209** [chaoss/wg-dei#473]
# Summary
I was trying to sign up for the Chaoss DEI WG mailing list linked in the [README](https://github.com/chaoss/wg-dei#contributing). This doesn't seem to exist anymore on the LF lists.

# Background
I was trying to sign up for the Chaoss DEI WG mailing list linked in the [README](https://github.com/chaoss/wg-dei#contributing). This doesn't seem to exist anymore on the LF lists. It could cause confusion for people looking to sign up. Additionally, I also noticed that on [the KB page](https://chaoss.community/kb-chaoss-community/), the mailing list seems to have been struck off. 

# Details
Modifying the GitHub README to either reflect the strike off or removing the entry completely would be the best way forward. However, since I'm relatively new I am unsure of the exact specifics of what could be implemented.

# Outcome
Better clarity for newcomers like myself, I guess?

**Comment by germonprez** [comment]
Thanks for this issue @divya-mohan0209 

Looking a bit more, @ElizabethN  -- I'd suggest that we put the DEI README on this week's agenda. I think the entire thing could use a little attention.

**Comment by divya-mohan0209** [comment]
I won't be able to attend the meeting, since it's at a very inconvenient hour for me. However, I can check the notes & work on revamping the DEI README if a consensus is reached.

**Comment by germonprez** [comment]
No problem! We will talk about it there and then update this issue and respond in Slack as well.
