### ISSUE TITLE
New Metric: Public Health and Safety

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/wg-dei#474]
This issue is created to collect comments on the Public Health and Safety metric

This metric can be found here: <<LINK TO MARKDOWN VERSION OF THE METRIC>>

## CHAOSS Metric Quality Checklist
This checklist is used for new metrics to ensure we follow CHAOSS quality standards and processes. 

### Process

- [ ] Add the new metric to release notes issue in working group repo
- [x] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit) to indicate that the metric is under community review.

**When above steps are completed:**

### Content Quality

- [x] Required headings are filled in
- [x] If any, ensure links to other CHAOSS metrics work
- [x] Optional headings that have no content are removed
- [x] Contributors section lists those contributors that want to be named
- [x] The name of the metric is the same in all locations

### Technical Requirements

- Message that the metric will be part of the next regular release is at top of page: 

### This metric is a release candidate. To comment on this metric please see Issue [#[put the respective Issue Number here]](URL to issue). Following a comment period, this metric will be included in the next regular release.

- Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- Images are included using markdown and absolute links (as described in the metrics template)
- Images have at least one empty line above and below them
- Ensure images are placed in image folder and followed [naming convention](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
- Ensure tables within metric are converted as images and placed in the image folder (both original MD and screenshotted PNG format) and follow the naming convention
- No HTML code in the metrics markdown.

**Comment by ElizabethN** [comment]
This metric has been published here: https://chaoss.community/kb/metric-public-health-and-safety/

**Comment by germonprez** [comment]
No feedback during the period. Closing issue.
